### ISSUE TITLE
Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by Obi-Wan-KeRobb** [BeepIsla/omegle-spam#1]
hi,
I follow the readme for set and use the bot, but when I launch the command node index.js appear this error

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\marianir\Downloads\omegle-spam-master\index.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

How to fix this?

**Comment by BeepIsla** [comment]
Update NodeJS
